"""Deploy — 一键部署到远程主机。

封装了以下经验 (ROADMAP.md §2):
  - SCHTASKS 定时任务 Windows 持久化
  - firewall 规则自动化
  - agent.bat 模板
  - Python wheel 分发
"""
import logging
import subprocess
from pathlib import Path
from typing import Optional

log = logging.getLogger("deploy")


AGENT_BAT_TEMPLATE = r"""@echo off
REM go-analyzer worker agent — auto-generated by Deploy
cd /d {WORKDIR}
call .venv\Scripts\activate.bat
python -m go_analysis.distributed.worker ^\
    --coordinator-url {COORDINATOR_URL} ^\
    --sgf-dir ./training ^
    --store-dir ./analysis_store ^
    --katago ./katago/katago.exe ^
    --model ./katago/{MODEL_FILE} ^
    --config ./katago/analysis_config.cfg ^
    --visits 25 --min-moves 10
"""

FIREWALL_PS1 = r"""netsh advfirewall firewall add rule name=GoAnalyzer_{{PORT}} \
    dir=in action=allow protocol=TCP localport={{PORT}}
"""

SCHTASKS_PS1 = r"""schtasks /create /tn GoAgent_{NAME} /tr "{WORKDIR}\agent.bat" \
    /sc onstart /ru SYSTEM /rl HIGHEST /f
schtasks /change /tn GoAgent_{NAME} /ri 10 /du 72:00
"""


class Deployer:
    """一键部署工具。"""

    def __init__(self, workdir: str, coordinator_url: str,
                 worker_id: str):
        self.workdir = Path(workdir).resolve()
        self.coordinator_url = coordinator_url
        self.worker_id = worker_id

    def generate_agent_bat(self, model_file: str = "model.bin.gz") -> str:
        """生成 agent.bat。"""
        content = AGENT_BAT_TEMPLATE.format(
            WORKDIR=str(self.workdir),
            COORDINATOR_URL=self.coordinator_url,
            WORKER_ID=self.worker_id,
            MODEL_FILE=model_file,
        )
        return content

    def generate_firewall_script(self, port: int = 18081) -> str:
        """生成防火墙脚本 (PowerShell)。"""
        return FIREWALL_PS1.replace("{{PORT}}", str(port))

    def generate_schtasks_script(self) -> str:
        """生成 SCHTASKS 注册脚本 (PowerShell)。"""
        return SCHTASKS_PS1.replace("{NAME}", self.worker_id)\
                           .replace("{WORKDIR}", str(self.workdir))

    def build_wheel(self, project_dir: str, output_dir: str = "dist") -> str:
        """构建 Python wheel 包。"""
        result = subprocess.run(
            ["uv", "build", "--out-dir", output_dir],
            cwd=project_dir, capture_output=True, text=True, timeout=120,
        )
        if result.returncode != 0:
            raise RuntimeError(f"Build failed: {result.stderr}")
        # 查找生成的 wheel
        dist = Path(output_dir)
        wheels = list(dist.glob("*.whl"))
        if wheels:
            return str(wheels[0])
        raise FileNotFoundError("No wheel produced")

    def deploy_via_scp(self, host: str, wheel_path: str, python_cmd: str = "python3"):
        """通过 SSH 部署 wheel 到远程主机。"""
        remote_dir = str(self.workdir)
        # 创建远程目录
        subprocess.run(
            ["ssh", host, f"mkdir -p {remote_dir}/katago {remote_dir}/training"],
            check=True, timeout=30,
        )
        # 上传 wheel
        subprocess.run(
            ["scp", wheel_path, f"{host}:{remote_dir}/"],
            check=True, timeout=60,
        )
        # 远程安装
        subprocess.run(
            ["ssh", host,
             f"cd {remote_dir} && {python_cmd} -m pip install --upgrade *.whl"],
            check=True, timeout=120,
        )
        log.info(f"Deployed wheel to {host}:{remote_dir}")
